apiVersion: miempresa.io/v1alpha1
kind: AppConfig
metadata:
  name: mi-app-dev-secret
  namespace: default
spec:
  entorno: "desarrollo"
  puerto: 8080
  generarSecretos: true
  writeConnectionSecretToRef:
    name: mi-app-credenciales-conn